---
#
# Installing Metricbeat
#

# Install Metricbeat 

- name: Install Metricbeat with apt
  apt:
   name: metricbeat
   update_cache: yes
    
# Starting Metricbeat
- name: Starting and Enbling Metricbeat at Startup
  service:
   name: metricbeat
   state: started
   enabled: yes

# - name: Enabling Metricbeat Startup
#   service:
#    name: metricbeat
#    state: started
